name: platynereis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - scipy=1.14.0
  - seaborn=0.13.2
  - pillow=10.4.0
  - pymc=5.16.1
  - arviz=0.18.0
  - ipykernel=6.29.4
  - statsmodels=0.14.1
  - tqdm=4.38.0
  - jupyterlab=4.2.4
  - ipywidgets=8.1.2
  - h5py=3.11.0
  - xarray=2024.7.0
  - graphviz=12.0.0
  - python-graphviz=0.20.3
  - m2w64-toolchain  # [win]

